server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # System logs
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          host: monitoring
          __path__: /var/log/*.log

  # Systemd journal logs
  - job_name: systemd-journal
    journal:
      json: false
      max_age: 12h
      path: /var/log/journal
      labels:
        job: systemd-journal
        host: monitoring
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'
      - source_labels: ['__journal__hostname']
        target_label: 'hostname'
      - source_labels: ['__journal_priority_keyword']
        target_label: 'level'

  # Docker container logs (json-file)
  - job_name: docker-container
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
    # Ambil container name
      - source_labels: ['__meta_docker_container_name']
        target_label: container
        regex: '/(.*)'
        replacement: '$1'

    # Ambil image
      - source_labels: ['__meta_docker_container_image']
        target_label: image

    # Mapping path log container
      - source_labels: ['__meta_docker_container_id']
        target_label: __path__
        replacement: /var/lib/docker/containers/$1/*-json.log

      - target_label: job
        replacement: docker-container

      - target_label: host
        replacement: monitoring

    pipeline_stages:
      - docker: {}







      #docker_sd_configs:
      #- host: unix:///var/run/docker.sock
        #refresh_interval: 5s
    #relabel_configs:
      #- source_labels: ['__meta_docker_container_name']
        #regex: '/(.*)'
        #target_label: 'container'
      #- source_labels: ['__meta_docker_container_log_stream']
        #target_label: 'logstream'
      #- source_labels: ['__meta_docker_container_id']
        #target_label: 'container_id'
